on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: 'Print befor'
        run: ls

      - uses: actions/checkout@v3 
      - name: "Login to Docker hub"
        run: docker login --username ${{secret.USER_NAME}} --password ${{secret.TOKEN}}