on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: 'Print befor'
        run: ls

      - uses: actions/checkout@v3 
      - name: 'Print after'
        run: ls 
      