on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: 'Print befor'
        run: ls

      - uses: actions/checkout@v3 
      - name: "Login to Docker hub"
        run: docker login --username fatmaahmed611 --password dckr_pat_OiJbcgQJ1yz9m2z1K12YH4Cd8Gg
      