on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: 'Print befor'
        run: ls

      - uses: actions/checkout@v3 
      - name: "Login to Docker hub"
        run: docker login --username ${{secrets.DOKER_USERNAME}} --password ${{secrets.DOCKER_PASSWORD}}

      - name: "Building image"
        run: docker build -t ${{secrets.DOKER_USERNAME}}/myimage .

      - name: "Pushing to docker hub"
        run: docker push ${{secrets.DOKER_USERNAME}}/myimage 